server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8081}

grpc:
  server:
    port: ${GRPC_SERVER_PORT:9091}

spring:
  application:
    name: reservation-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/sportik-backend}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:taha1111}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  output:
    ansi:
      enabled: always

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://localhost:4317}
      transport: grpc

app:
  business:
    reservation-active-time-sec: 600
  security:
    public-paths:
      - /swagger-ui/**
      - /v3/api-docs/**
      - /api/reservations/mock-gateway/info/**
    jwt:
      public-key: classpath:keys/public_key.pem
      issuer: backend-service