spring.application.name=backend

# server
server.address=localhost
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/phfit-app-backend

spring.datasource.username=postgres
spring.datasource.password=taha1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# app.security
app.security.public-paths=/api/auth/**,/error
app.security.jwt.private-key=classpath:keys/private_key.pem
app.security.jwt.public-key=classpath:keys/public_key.pem
app.security.jwt.access-token-expiration-sec=900
app.security.jwt.refresh-token-expiration-sec=2592000
app.security.jwt.issuer=backend-service
app.security.jwt.audience=frontend
