server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: backend
  datasource:
    # TODO: change this part when it wants to run in container
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/phfit-app-backend}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:taha1111}
  jpa:
    hibernate:
      # TODO: Change it in server
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  output:
    ansi:
      enabled: always

  # Connect to redis
  data:
    redis:
      # TODO: change this part when it wants to run in container
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

app:
  security:
    public-paths: /api/v1/auth/**,/error
    jwt:
      private-key: classpath:keys/private_key.pem
      public-key: classpath:keys/public_key.pem
      access-token-expiration-sec: 900
      refresh-token-expiration-sec: 2592000
      issuer: backend-service
      audience: frontend