spring.application.name=backend

# server
server.address=localhost
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/phfit-app-backend

spring.datasource.username=postgres
spring.datasource.password=taha1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# app.security
app.security.jwt.secret=abc123
app.security.jwt.access-token-expiration-sec=900
app.security.jwt.refresh-token-expiration-sec=2592000
