spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/phfit-app-backend
# TODO: in server, chane user and pass to environment var
spring.datasource.username=postgres
spring.datasource.password=taha1111
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true