<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <UserSecretsId>b39df5b7-c72f-4061-9a32-ac444cbff128</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="..\..\..\.dockerignore">
            <Link>.dockerignore</Link>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="MailKit" Version="4.17.0"/>
        <PackageReference Include="Resend" Version="0.8.0"/>
        <PackageReference Include="Grpc.AspNetCore" Version="2.71.0"/>
        <PackageReference Include="Grpc.AspNetCore.Server.Reflection" Version="2.80.0"/>
        <PackageReference Include="Grpc.Tools" Version="2.71.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Services/GrpcService/protos/notification.proto" GrpcServices="Server"/>
    </ItemGroup>


</Project>
